### ISSUE TITLE
wrong path to autoload.php on mod_form.php and view.php

### ISSUE THREAD

**Issue by yedidiaklein** [UCA-Squad/moodle-mod_teams#2]
plz see https://github.com/UCA-Squad/moodle-mod_teams/pull/1
should be $CFG->dirroot . '/mod/teams/vendor/' . autoload.php

**Comment by andurif** [comment]
Hello,
Sorry for the late answer and the late dealing of the issue. We accepted your PR, thanks for your proposition.
