### ISSUE TITLE
Capabilities for meetings and teams

### ISSUE THREAD

**Issue by MURBASLMS** [UCA-Squad/moodle-mod_teams#4]
Hi, it would be good to be able to disable the creating teams element, so having capabilities to control what displays would be a good option. 

For this we'd like to just to have creating meetings available for teaching staff.

Cheers

**Comment by andurif** [comment]
Hello @MURBASLMS ,
Sorry for the very late answer. Thanks for your suggestion.

In the last release we added two different capabilites, one per type of ressource (team and meeting) to indicate the possibility to create/edit each resource. For your ask if you disable the creating teams capability you will only be able to select meeting resource in the form.
For information we also created another plugin which only permits to create Teams online meeting, maybe this can help you (be careful, warnings can appear if you install the two plugins in the same platform). Here is the link of the plugin: https://github.com/UCA-Squad/moodle-mod_teamsmeeting 

Feel free to do other suggestion or tell us if you have problems.
Cheers,
Anthony
